### ISSUE TITLE
Use of env or config

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [Cyb3r-Jak3/cloudflare-utils#5]
To simplify configuration, we should accept either a config file, probably YAML, or an .env file.

**Comment by StudioLE** [comment]
Both `.env` and `.yml` configuration are easily accomplished by using docker compose. It also cuts out the complexity of installing go etc. 

Here's an approximation of the workflow I'm using:

1. `docker-compose.yml`

```yml
version: "3"

services:
  version:
    image: cyb3rjak3/cloudflare-utils
    command: --version
    
  help:
    image: cyb3rjak3/cloudflare-utils
    command: --help
  
  download:
    image: cyb3rjak3/cloudflare-utils
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_ZONE_NAME: ${CLOUDFLARE_ZONE_NAME}
      LOG_LEVEL_VERBOSE: ${LOG_LEVEL_VERBOSE}
      LOG_LEVEL_DEBUG: ${LOG_LEVEL_DEBUG}
    command: dns-cleaner download
    volumes:
    - ./records/${CLOUDFLARE_ZONE_NAME}.yml:/dns-records.yml

  upload:
    image: cyb3rjak3/cloudflare-utils
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_ZONE_NAME: ${CLOUDFLARE_ZONE_NAME}
      LOG_LEVEL_VERBOSE: ${LOG_LEVEL_VERBOSE}
      LOG_LEVEL_DEBUG: ${LOG_LEVEL_DEBUG}
    command: dns-cleaner upload
    volumes:
    - ./records/${CLOUDFLARE_ZONE_NAME}.yml:/dns-records.yml

```

2. `.env`
```ini
CLOUDFLARE_API_TOKEN=
CLOUDFLARE_ZONE_NAME=
LOG_LEVEL_VERBOSE=true
LOG_LEVEL_DEBUG=true
```

3. Create an empty file for dns records

```bash
touch records/[YOUR_CLOUDFLARE_ZONE_NAME].yml
```

4. Run `dns-cleaner download`

```bash
docker compose run download
```

5. Edit the dns records file.

```bash
nano records/[YOUR_CLOUDFLARE_ZONE_NAME].yml
```

6. Run `dns-cleaner upload`

```bash
docker compose run upload
```
